# Generated by Django 5.0.4 on 2024-05-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fav', to='app1.event'),
        ),
    ]
